-- MySQL Script generated by MySQL Workbench
-- Wed Sep  8 11:48:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_fdje
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_fdje` ;

-- -----------------------------------------------------
-- Schema db_fdje
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_fdje` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_fdje` ;

-- -----------------------------------------------------
-- Table `db_fdje`.`ayudas_fundacions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`ayudas_fundacions` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`ayudas_fundacions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_ayuda` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`provincias` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`provincias` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`ciudades` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`ciudades` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `id_provincia` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ciudades_id_provincia_foreign` (`id_provincia` ASC) VISIBLE,
  CONSTRAINT `ciudades_id_provincia_foreign`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `db_fdje`.`provincias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 222
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`diabetes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`diabetes` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`diabetes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_diabetes` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`insulina_prandials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`insulina_prandials` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`insulina_prandials` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`insulinas_basal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`insulinas_basal` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`insulinas_basal` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`migrations` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`problema_diabetes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`problema_diabetes` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`problema_diabetes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `problema` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`tipo_hospitales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`tipo_hospitales` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`tipo_hospitales` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_hospitales` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`pacientes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(15) NOT NULL,
  `nombres` VARCHAR(120) NOT NULL,
  `apellidos` VARCHAR(120) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `lugar_nacimiento` VARCHAR(50) NOT NULL,
  `fecha_diagnostico_diabetes` DATE NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `telefono_convencional` VARCHAR(15) NOT NULL,
  `valor_hemoglobina` INT(11) NOT NULL,
  `veces_mide_glucosa` INT(11) NOT NULL,
  `tiene_registro_glucosa` VARCHAR(50) NOT NULL,
  `puede_medir_glucosa` VARCHAR(50) NOT NULL,
  `dosis_insulina_basal` VARCHAR(120) NOT NULL,
  `dosis_insulina_prandial` VARCHAR(120) NOT NULL,
  `sintoma_frente_hipoglucemia` INT(11) NOT NULL,
  `veces_hipoglucemia_menos` INT(11) NOT NULL,
  `mas_baja_hipoglucemia` INT(11) NOT NULL,
  `administra_hipoglucemia` INT(11) NOT NULL,
  `tiene_convulsiones` TINYINT(1) NOT NULL,
  `nombres_medico` VARCHAR(200) NOT NULL,
  `fecha_ultima_cita` DATE NOT NULL,
  `nombre_hospital` VARCHAR(200) NOT NULL,
  `cedula_representante` VARCHAR(15) NOT NULL,
  `nombres_representante` VARCHAR(255) NOT NULL,
  `celular_representante` VARCHAR(15) NOT NULL,
  `solicita_ayuda_fundacion` TINYINT(1) NOT NULL,
  `otra_enfermedad` VARCHAR(200) NOT NULL,
  `cantidad_familia` INT(11) NOT NULL,
  `cantidad_menores_edad` INT(11) NOT NULL,
  `algun_discapacitado_familia` VARCHAR(150) NOT NULL,
  `zona_vive` VARCHAR(40) NOT NULL,
  `tipo_vivienda` VARCHAR(45) NOT NULL,
  `personas_aportan_familia` INT(11) NOT NULL,
  `situacion_jefe_hogar` VARCHAR(40) NOT NULL,
  `id_ciudad` BIGINT(20) UNSIGNED NOT NULL,
  `id_diabetes` BIGINT(20) UNSIGNED NOT NULL,
  `id_insulina_basals` BIGINT(20) UNSIGNED NOT NULL,
  `id_insulina_prandials` BIGINT(20) UNSIGNED NOT NULL,
  `id_tipo_hospitales` BIGINT(20) UNSIGNED NOT NULL,
  `id_ayudas_fundacions` BIGINT(20) UNSIGNED NOT NULL,
  `id_problema_diabetes` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pacientes_cedula_unique` (`cedula` ASC) VISIBLE,
  UNIQUE INDEX `pacientes_email_unique` (`email` ASC) VISIBLE,
  INDEX `pacientes_id_ciudad_foreign` (`id_ciudad` ASC) VISIBLE,
  INDEX `pacientes_id_diabetes_foreign` (`id_diabetes` ASC) VISIBLE,
  INDEX `pacientes_id_insulina_basals_foreign` (`id_insulina_basals` ASC) VISIBLE,
  INDEX `pacientes_id_insulina_prandials_foreign` (`id_insulina_prandials` ASC) VISIBLE,
  INDEX `pacientes_id_tipo_hospitales_foreign` (`id_tipo_hospitales` ASC) VISIBLE,
  INDEX `pacientes_id_ayudas_fundacions_foreign` (`id_ayudas_fundacions` ASC) VISIBLE,
  INDEX `pacientes_id_problema_diabetes_foreign` (`id_problema_diabetes` ASC) VISIBLE,
  CONSTRAINT `pacientes_id_ayudas_fundacions_foreign`
    FOREIGN KEY (`id_ayudas_fundacions`)
    REFERENCES `db_fdje`.`ayudas_fundacions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_ciudad_foreign`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `db_fdje`.`ciudades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_diabetes_foreign`
    FOREIGN KEY (`id_diabetes`)
    REFERENCES `db_fdje`.`diabetes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_insulina_basals_foreign`
    FOREIGN KEY (`id_insulina_basals`)
    REFERENCES `db_fdje`.`insulinas_basal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_insulina_prandials_foreign`
    FOREIGN KEY (`id_insulina_prandials`)
    REFERENCES `db_fdje`.`insulina_prandials` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_problema_diabetes_foreign`
    FOREIGN KEY (`id_problema_diabetes`)
    REFERENCES `db_fdje`.`problema_diabetes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_tipo_hospitales_foreign`
    FOREIGN KEY (`id_tipo_hospitales`)
    REFERENCES `db_fdje`.`tipo_hospitales` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fdje`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fdje`.`users` ;

CREATE TABLE IF NOT EXISTS `db_fdje`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
