-- MySQL Script generated by MySQL Workbench
-- Sun Sep 12 13:17:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_fundacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_fundacion` ;

-- -----------------------------------------------------
-- Schema db_fundacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_fundacion` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_fundacion` ;

-- -----------------------------------------------------
-- Table `db_fundacion`.`ayuda_fundacions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`ayuda_fundacions` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`ayuda_fundacions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_ayuda` VARCHAR(120) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`provincias` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`provincias` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`ciudads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`ciudads` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`ciudads` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(80) NOT NULL,
  `id_provincia` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ciudads_id_provincia_foreign`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `db_fundacion`.`provincias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 222
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`diabetes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`diabetes` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`diabetes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_diabetes` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`insulina_basals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`insulina_basals` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`insulina_basals` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`insulina_prandials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`insulina_prandials` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`insulina_prandials` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`medicos` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`medicos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(75) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`migrations` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(191) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`tipo_hospitals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`tipo_hospitals` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`tipo_hospitals` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_hospital` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`pacientes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(15) NULL DEFAULT NULL,
  `nombres` VARCHAR(100) NULL DEFAULT NULL,
  `apellidos` VARCHAR(75) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `lugar_nacimiento` VARCHAR(40) NULL DEFAULT NULL,
  `fecha_diagnostico_diabetes` DATE NULL DEFAULT NULL,
  `celular` VARCHAR(15) NULL DEFAULT NULL,
  `telefono_convencional` VARCHAR(15) NULL DEFAULT NULL,
  `valor_hemoglobina` VARCHAR(10) NULL DEFAULT NULL,
  `fecha_ultimo_examen_hemoglobina` DATE NULL DEFAULT NULL,
  `veces_mide_glucosa` INT(11) NULL DEFAULT NULL,
  `tiene_registro_glucosa` VARCHAR(10) NULL DEFAULT NULL,
  `puede_medir_glucosa` VARCHAR(10) NULL DEFAULT NULL,
  `dosis_insulina_basal` VARCHAR(200) NULL DEFAULT NULL,
  `dosis_insulina_prandial` VARCHAR(200) NULL DEFAULT NULL,
  `sintoma_frente_hipoglucemia` VARCHAR(10) NULL DEFAULT NULL,
  `veces_hipoglucemia_menos` INT(11) NULL DEFAULT NULL,
  `mas_baja_hipoglucemia` INT(11) NULL DEFAULT NULL,
  `administra_hipoglucemia` VARCHAR(120) NULL DEFAULT NULL,
  `tiene_convulsiones` VARCHAR(10) NULL DEFAULT NULL,
  `fecha_ultima_cita` DATE NULL DEFAULT NULL,
  `nombre_hospital` VARCHAR(120) NULL DEFAULT NULL,
  `cedula_representante` VARCHAR(15) NULL DEFAULT NULL,
  `nombres_representante` VARCHAR(75) NULL DEFAULT NULL,
  `celular_representante` VARCHAR(15) NULL DEFAULT NULL,
  `solicita_ayuda_fundacion` VARCHAR(10) NULL DEFAULT NULL,
  `otra_enfermedad` VARCHAR(10) NULL DEFAULT NULL,
  `cantidad_familia` INT(11) NULL DEFAULT NULL,
  `cantidad_menores_edad` INT(11) NULL DEFAULT NULL,
  `algun_discapacitado_familia` VARCHAR(50) NULL DEFAULT NULL,
  `zona_vive` VARCHAR(30) NULL DEFAULT NULL,
  `tipo_vivienda` VARCHAR(50) NULL DEFAULT NULL,
  `personas_aportan_familia` INT(11) NULL DEFAULT NULL,
  `situacion_jefe_hogar` VARCHAR(35) NULL DEFAULT NULL,
  `problemas_diabetes` VARCHAR(60) NULL DEFAULT NULL,
  `id_ciudad` BIGINT(20) UNSIGNED NOT NULL,
  `id_diabetes` BIGINT(20) UNSIGNED NOT NULL,
  `id_insulina_basals` BIGINT(20) UNSIGNED NOT NULL,
  `id_insulina_prandials` BIGINT(20) UNSIGNED NOT NULL,
  `id_tipo_hospital` BIGINT(20) UNSIGNED NOT NULL,
  `id_ayuda_fundacion` BIGINT(20) UNSIGNED NOT NULL,
  `id_medico` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `pacientes_id_ayuda_fundacion_foreign`
    FOREIGN KEY (`id_ayuda_fundacion`)
    REFERENCES `db_fundacion`.`ayuda_fundacions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_ciudad_foreign`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `db_fundacion`.`ciudads` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_diabetes_foreign`
    FOREIGN KEY (`id_diabetes`)
    REFERENCES `db_fundacion`.`diabetes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_insulina_basals_foreign`
    FOREIGN KEY (`id_insulina_basals`)
    REFERENCES `db_fundacion`.`insulina_basals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_insulina_prandials_foreign`
    FOREIGN KEY (`id_insulina_prandials`)
    REFERENCES `db_fundacion`.`insulina_prandials` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_medico_foreign`
    FOREIGN KEY (`id_medico`)
    REFERENCES `db_fundacion`.`medicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pacientes_id_tipo_hospital_foreign`
    FOREIGN KEY (`id_tipo_hospital`)
    REFERENCES `db_fundacion`.`tipo_hospitals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`password_resets` (
  `email` VARCHAR(191) NOT NULL,
  `token` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_fundacion`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_fundacion`.`users` ;

CREATE TABLE IF NOT EXISTS `db_fundacion`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(191) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
  )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;
